### ISSUE TITLE
Example in README has an error

### ISSUE THREAD

**Issue by altano** [tableau/ts-checked-fsm#22]
I stuck your README example in a codesandbox and it has an error on [this line](https://github.com/tableau/ts-checked-fsm/blob/master/Readme.md?plain=1#L74).

The error:
> (parameter) c: State<"get-money", MoneyPayload>
> A 'const' assertions can only be applied to references to enum members, or string, number, boolean, array, or object literals.ts(1355)

Sandbox: https://codesandbox.io/s/agitated-gwen-4ri166?file=/src/ts-checked-fsm.ts

It's using TS 4.5.5 and I made sure the tsconfig.json matches for the options that matter.

**Comment by rickwebiii** [comment]
Thanks for the report. Fixed.
