### ISSUE TITLE
Error on invalid actions?

### ISSUE THREAD

**Issue by altano** [tableau/ts-checked-fsm#23]
In the README example the first action states:

```typescript
let n = nextState({ stateName: "idle" }, { actionName: "clock-tick" });
// Idle state doesn't repsond to clock-tick, so state is unchanged
```

Would it make sense to (and is it possible to) error on this instead? Silently discarding actions on state that is unresponsive to that action can lead to errors.

Thanks for this library and for the amazing companion article, btw. I've learned a ton about TS.

**Comment by altano** [comment]
Now that I think about it, even if you could figure out the set of valid actions when you have access to the current state, this probably isn't widely usable. For example, if you used `nextState` as a React reducer, you pass around a `dispatch` function that anyone can dispatch to. And I think there's no way to make the dispatch function dynamically typed based on the current action?

**Comment by rickwebiii** [comment]
You might be able to get halfway there for the external API of your state machine. You could make `.action` take a union of states that handle it and can make it an error if you call next state where current state isn't in that set of states for the action.

However, there's no way to assert your state machine does or does not actually handle that action.

But in any case, one of the main powers of an FSM is ignoring inputs you don't know how to handle. Consider a video game. A player can jump while in the standing state and transition to the jumping state. While in the jumping state, nothing stops the user from attempting to jump again, but the FSM will ignore the input. Thus, sending actions to and FSM only for it to ignore them is often desirable, even if the FSM doesn't explicitly handle them with a self-transition.
